language: python
python: 3.6
os:
    - linux

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds. A full list of packages
# that can be included can be found here:
#
# https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise

addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

services:
  - mysql

env:
    global:
        - NUMPY_VERSION=1.15.1
        - PYTHON_INSTALL_COMMAND='python setup.py install'
        - SETUP_CMD = ''
        - RUN_TESTS=1
        - INSTALL_DEPS=1
        - MAIN_CMD='python setup.py'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
        - env: SETUP_CMD='egg_info' RUN_TESTS=0 PYTHON_INSTALL_COMMAND='true' INSTALL_DEPS=0

        - python: 3.6
          env: SETUP_CMD='egg_info' RUN_TESTS=0 PYTHON_INSTALL_COMMAND='true' INSTALL_DEPS=0

        - env: RUN_TESTS=1

        # Do a coverage test.
        - os: linux
          env: MAIN_CMD='coverage run setup.py'

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        - os: linux
          env: SETUP_CMD='build_sphinx' RUN_TESTS=0

        # Try all python versions and Numpy versions. Since we can assume that
        # the Numpy developers have taken care of testing Numpy with different
        # versions of Python, we can vary Python and Numpy versions at the same
        # time.
        - os: linux
          env: NUMPY_VERSION=1.13
        - os: linux
          env: NUMPY_VERSION=1.14
        - os: linux
          env: NUMPY_VERSION=1.15

        # Do a PEP8 test with pycodestyle
        - os: linux
          env: MAIN_CMD='pycodestyle banzai_nres --count' RUN_TESTS=0

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then security set-key-partition-list -S 'apple-tool:,apple:' -s -k keychainPass keychainName; fi


install:
  - if [[ "$INSTALL_DEPS" == 1 ]]; then pip install numpy==$NUMPY_VERSION coverage pycodestyle; fi
  - $PYTHON_INSTALL_COMMAND

script:
   - if [[ "$RUN_TESTS" == 1 ]]; then SETUP_ARRAY=(test --addopts '-m "not e2e"'); else SETUP_ARRAY=(); fi
   - $MAIN_CMD "${SETUP_ARRAY[@]}" $SETUP_CMD

after_success:
    - if [[ "$MAIN_CMD" == 'coverage run setup.py' ]]; then coveralls --rcfile='banzai_nres/tests/coveragerc'; fi
