dependencies:
- name: postgresql
  version: 8.1.5
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: useDockerizedDatabase

- name: rabbitmq
  version: 3.8.3
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: useDockerizedRabbitMQ
