# Production deployment values for BANZAI-NRES.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Automatically manage worker count within the configured limits. More workers
# will be started when the CPU usage rises above the configured threshold.
horizontalPodAutoscaler:
  enabled: true
  minReplicas: 6
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50

image:
  repository: docker.lco.global/banzai-nres
  tag: "1.0.0"
  pullPolicy: IfNotPresent

# Values for the OCS Ingester library, used by BANZAI-NRES.
ingester:
  apiRoot: http://archiveapi-internal.prod/
  s3Bucket: archive-lco-global
  ingesterProcessName: banzai_nres
  opentsdbHostname: opentsdb.lco.gtn
  opentsdbPort: 80
  postProcessFiles: false
  noMetrics: false

# Values specific to the BANZAI-NRES pipeline
banzaiNres:
  astrometryServiceUrl: http://astrometry.lco.gtn/catalog
  configdbUrl: http://configdb.lco.gtn/sites/
  observationPortalUrl: http://internal-observation-portal.lco.gtn/api/observations/
  useDifferentArchiveSources: false
  calibrateProposalId: calibrate
  banzaiWorkerLogLevel: info
  rawDataApiRoot: http://archiveapi-internal.prod/
  fitsBroker: rabbitmq.lco.gtn
  fitsExchange: archived_fits
  queueName: banzai_nres_pipeline
  phoenixFileLocation: s3://banzai-nres-phoenix-models-lco-global
  celeryTaskQueueName: banzai_nres

# CronJob configuration to periodically update instrument table in BANZAI DB
instrumentTableCronjob:
  schedule: "*/5 * * * *"

useDockerizedDatabase: false
useDockerizedRabbitMQ: false

postgresql:
  hostname: postgres1-cluster.cluster-cple9sjsskrf.us-west-2.rds.amazonaws.com
  postgresqlUsername: banzai-nres
  postgresqlDatabase: banzai-nres

rabbitmq:
  hostname: rabbitmq-ha.prod.svc.cluster.local.
  rabbitmq:
    username: banzai
  vhost: banzai
