# Default values for banzai-nres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workerCount: 4

image:
  repository: docker.lco.global/banzai-nres
  tag: latest
  pullPolicy: IfNotPresent

nodeSelector: {}

tolerations: []

affinity: {}

CALIBRATE_PROPOSAL_ID: calibrate

OBSERVATION_PORTAL_URL: http://internal-observation-portal.lco.gtn/api/observations/

API_ROOT: http://banzai-nres-archive-api.lco.gtn/

BUCKET: banzai-nres-lco-global

RAW_DATA_FRAME_URL: "http://archiveapi-internal/"

INGESTER_PROCESS_NAME: "banzai-nres-dev"

NO_METRICS: true

OPENTSDB_HOSTNAME: opentsdb.lco.gtn

BOSUN_HOSTNAME: alerts.lco.gtn

FITS_BROKER: rabbitmq.lco.gtn

FITS_EXCHANGE: archived_fits

useDockerizedDatabase: true

postgresql:
  hostname: "db.example.com"
  postgresqlUsername: "banzainres"
  postgresqlDatabase: "banzainres"
  existingSecret: "banzai-nres-secrets"

useDockerizedRabbitMQ: true

rabbitmq:
  username: "user"
  vhost: ""
  existingPasswordSecret: "banzai-nres-secrets"

configdb_url: "http://configdb.lco.gtn/sites/"
