name: 'Run E2E Step'
description: 'Executes a specific pytest marker and logs results.'
inputs:
  pod_name:
    description: 'The name of the banzai-nres-e2e pod.'
    required: true
  test_marker:
    description: 'The pytest marker to execute (e.g., master_bias).'
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set +e
        export START=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
        kubectl exec ${{ inputs.pod_name }} -c banzai-nres-e2e-listener -- pytest -s --pyargs banzai_nres --durations=0 -m ${{ inputs.test_marker }}
        EXIT_CODE=$?

        echo "::group::Logs for ${{ inputs.test_module }}"
        # Always print logs even if (especially if?) the reduction fails
        kubectl logs ${{ inputs.pod_name }} -c banzai-nres-e2e-listener --since-time=$START --prefix=true
        kubectl logs ${{ inputs.pod_name }} -c banzai-nres-e2e-celery-workers --since-time=$START --prefix=true
        echo "::endgroup::"

        # Exit with the captured status so the job properly fails or succeeds
        exit $EXIT_CODE
