name: Docs

on:
  pull_request:
    branches:
        - '*'
  push:
    branches:
        - 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Or macos-latest if needed

    steps:
      - uses: actions/checkout@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: '3.12'
      - name: Set up project
        run: uv sync --extra docs
      - name: Install pandoc
        run: sudo apt-get update
      - name: Install pandoc
        run: sudo apt-get install pandoc
      - name: Build Docs
        run: uv run sphinx-build -W -b html docs docs/_build/html
